

export var CryptoDescription={
    "Bitcoin": "The king of the crypto world, Bitcoin is now a household name; to many, it is synonymous with “cryptocurrency.” Its purpose is to provide a peer-to-peer electronic version of cash to allow payments to be sent online without the need for a third party (such as Mastercard).\n\nThe rapid rise in Bitcoin’s price has brought about an explosion of new Bitcoin investors. With the huge increase in interest has come a rise in merchants accepting Bitcoin as a legitimate form of payment. Bitcoin is fast moving towards its goal of becoming a currency accepted worldwide.\n\nBitcoin’s development is led by Bitcoin Core developer Wladimir J. van der Laan, who took over the role on April 8, 2014. Bitcoin’s changes are decided democratically by the community.",

    "Ethereum": "Ethereum is the revolutionary platform which brought the concept of “smart contracts” to the blockchain. First released to the world in July 2015 by then 21-year-old Vitalik Buterin, Ethereum has quickly risen from obscurity to cryptocurrency celebrity status.\n\nButerin has a full team of developers working behind him to further develop the Ethereum platform. For more background information on Buterin, read our article, “Vitalik Buterin: The Face of Blockchain.”\n\nEthereum has the ability to process transactions quickly and cheaply over the blockchain similar to Bitcoin, but also has the ability to run smart contracts. For future reading on smart contracts, see “What’s the Difference Between Bitcoin and Ethereum” but for now, think automated processes which can do just about anything.",

    "Bitcoin Cash": "Bitcoin Cash was created on August 1, 2017 after a “hard fork” of the Bitcoin blockchain. For years, a debate has been raging in the Bitcoin community on whether to increase the block size in the hope of alleviating some of the network bottleneck which has plagued Bitcoin due to its increased popularity.\n\nBecause no agreement could be reached, the original Bitcoin blockchain was forked, leaving the Bitcoin chain untouched and in effect creating a new blockchain which would allow developers to modify some of Bitcoin’s original programmed features.\n\nGenerally speaking, the argument for Bitcoin Cash is that by allowing the block size to increase, more transactions can be processed in the same amount of time. Those opposed to Bitcoin Cash argue that increasing the block size will increase the storage and bandwidth requirement, and in effect will price out normal users. This could lead to increased centralization, the exact thing Bitcoin set out to avoid.\n\nBitcoin Cash does not have one single development team like Bitcoin. There are now multiple independent teams of developers.",

    "Litecoin":"Similar to Bitcoin, Litecoin is a peer-to-peer transaction platform designed to be used as a digital currency. Due to some notable technical improvements, Litecoin is able to handle more transactions at lower costs. Litecoin has been designed to process the small transactions we make daily.\n\nThe Litecoin blockchain is a fork from the Bitcoin chain. It was initially launched in 2011 when its founder, Charlie Lee, was still working for Google. Well-known as a cryptocurrency expert, Charlie Lee is backed by a strong development team who appear to be achieving what they set out to do. They have recently achieved a very notable accomplishment with the first successful atomic swap\n\n.",

    "Dash":"Dash (which comes from “digital cash”) aims to be the most user-friendly and scalable cryptocurrency in the world. It has the ability to send funds instantly confirmed by “double-send-proof” security with the added functionality of erasable transaction history and the ability to send transactions anonymously.\n\nLike Bitcoin, Dash is meant to be used as a digital currency but has some added values such as much faster transaction times and lower fees. For a slightly higher fee, Dash has the added function of “instant send” which allows transactions to be confirmed almost instantly. This is one of the main selling points of Dash because many believe that this feature would allow it to be used in brick and mortar establishments.\n\nThe Dash development team consists of over 50 members and is led by former financial services professional Evan Duffield.",

    "Binance": "Binance Coin is the coin used to facilitate operations on the Binance platform, a cryptocurrency exchange that is capable of processing 1.4 million orders per second. The name “Binance” is derived from the combination of the terms “binary” and “finance,” referring to the integration of digital technology and finance.\n\nThe BNB coin is used to pay exchange fees, withdrawal fees, listing fees, and all other possible transaction expenses on the Binance platform. In order to incentivize new users to do their cryptocurrency trading on Binance, the team is offering discounts when BNB is used to pay fees. The discount will be 50% in the first year, 25% in the second, 12.5% in the third, and 6.25% in the fourth year before the discount ends.\n\nBinance was primarily marketed to Chinese cryptocurrency investors at first, but they also have English, Korean, Japanese, French, Spanish, and Russian versions of the platform.\n\n",

    "Ethereum Classic": "Ethereum Classic came about after a hard fork of Ethereum in 2016. The fork was a result of the infamous DOA hack where around 50 million dollars worth of Ethereum was stolen due to what was considered an oversight in the code.\n\nThe blockchain was forked in order to recoup the losses from this attack, but a small portion of the community did not wish to go back and change the original blockchain. Vitalik Buterin, founder of Ethereum, and subsequently the development team chose to go with the hard fork and work on what is now “Ethereum” today.\n\n",

    "0x": "0x is a decentralized exchange built on the Ethereum blockchain that allows for ERC20 tokens to be traded. 0x’s intention is to serve as a building block from which others can easily create their own decentralized exchangeOne of the key differences between 0x and other decentralized exchanges is that 0x is fast. To reduce blockchain bloat, all orders are transported off-blockchain and later verified. In addition to making transactions quick, this removes the necessity of spending gas to pay for network transaction costs, like on other decentralized exchanges such as EtherDelta.\n\n0x uses a open-source system of smart contracts which acts as an infrastructure for those wishing to build with the 0x protocol. A number of projects have already started building on the 0x platform already such as Augur, Aragon and Request Network.",

    "Decred": "Decred, which stands for decentralized credit, is a digital currency that uses a community-based governance model to determine the future of its blockchain protocol.\n\nDecred was created and designed with the core mission of solving the problem of blockchain governance. Bitcoin in particular has experienced a lot of problems with the community not being able to agree upon protocol changes. Issues such as the block size debate has split the community, with a resolution yet to be found.\n\nDecred employs a unique hybrid of PoW and PoS mining to decentralize the decision-making process. You can read more about this hybrid system in the Decred whitepaper.",

    "DigiByte": "DigiByte is an open-source blockchain which first came into existence in January 2014, making it one of the oldest blockchains in existence. It was founded by developer Jared Tate, who today still leads the project.\n\nDigiByte focuses on cybersecurity for digital payments and smart applications. It is highly decentralized with over 100,000+ servers, computers, phones, and nodes worldwide. DigiByte utilizes five secure and advanced cryptographic mining algorithms to prevent mining centralization which is common in single algorithm blockchains such as Bitcoin\n\n.In addition, DigiByte has some other technical improvements over Bitcoin such as increased scalability and the implementation of technologies such as Digishield, MultiAlgo, MultiShield and SegWit.",

    "ChainLink": "Chainlink is effectively applying smart contracts to the offline world by creating different APIs which will be compatible with off-chain-based software.\n\nToday, no one has been able to connect a smart contract with an external data feed. Solving this roadblock would be a big step forward for the world of blockchain, as it would provide many “low-tech” companies the ability to leverage the power of blockchain.\n\nChainlink aims to provide a solution as it is working on creating decentralized oracles which will allow non-blockchain based projects to interact with the Chainlink blockchain.\n\nChainlink has been staying under the radar, not hyping their project or putting too much time into marketing. However, with the announcement of partnerships with some well-known names in the crypto world such as Polkadot and Factom, people are starting to take notice.",
    
    "Augur": "Augur has set out to create the first decentralized, open-source platform for prediction markets. Based on the ideas of game theory and wisdom of the crowd, prediction markets achieve greater forecasting accuracy than any individual experts can. However, the problem with previously existing prediction markets is that they were all centralized.\n\nBy providing a decentralized solution, Augur allows people from anywhere in the world to ask a question about the outcome of a future event, as well as buy and sell shares on the outcome of any market they wish to participate in. Moreover, it allows thousands of users to report on outcomes, thus removing the need to trust in an individual reporter.\n\nAugur has assembled an experienced team of developers, led by co-founders Jack Peterson and Joey Krug. Additionally, they have several notable advisors including the founder of Ethereum, Vitalik Buterin, trading expert Ron Bernstein, economist Dr. Robin Hanson, CEO of Enlighted Joe Costello, and Lightning Network founder Elizabeth Stark.",

    "Bitcoin SV": "Bitcoin Satoshi’s Vision was created out of the hard fork of Bitcoin Cash (BCH) on November 15, 2018. A segment of the ecosystem wanted to increase the blocksize greater and faster as well as limit potential smart contract features. They split was led by nChain’s Chief Scientist, Craig Wright, who is also renowned for claiming he was Satoshi Nakamoto, the original founder of Bitcoin, without extensive evidence. Since it’s forking, it has consistently remained in the top 20 coins by market cap.\n\nIt also migrated businesses and developers from BCH to its ecosystem. It seeks to emulate the proposed original vision of bitcoin through emphasis on scaling onchain as fast as possible.",

    "Ripple": "Ripple aims to improve the speed of financial transactions, specifically international banking transactions.\n\nAnyone who has ever sent money internationally knows that today it currently takes anywhere from 3-5 business days for a transaction to clear. It is faster to withdraw money, get on a plane, and fly it to your destination than it is to send it electronically! Not to mention you will be paying exorbitant transaction fees, usually somewhere around 6% but it can vary depending on the financial institution\n\nRipple’s goal is to make these transactions fast (it only takes around 4 seconds for a transaction to clear) and chea\n\nThe Ripple team currently comprises over 150+ people, making it one of the biggest in the cryptocurrency world. They are led by CEO Brad Garlinghouse, who has an impressive resume which includes high positions in other organizations such as Yahoo and Hightail."
}
